[project]
name = "basic-rag"
version = "0.1.0"
description = "Project for study purposes"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "transformers",
    "faiss-cpu",
    "torch",
    "scikit-learn",
    "jupyter"
]
